### ISSUE TITLE
Allow to be used in other libraries

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-icons#3]
such as https://github.com/NG-ZORRO/ng-zorro-antd

cc @vthinkxie

**Comment by vthinkxie** [comment]
👏

**Comment by HeskeyBaozi** [comment]
## Adapters

We need helps from the community.

适配器的功能是将图标的`SVG`结构抽象树转换成对应框架的组件（或模块）。

## Library and Framework

### React
- [x] React Component: [@ant-design/icons-react](https://github.com/ant-design/ant-design-icons/tree/dev/packages/icons-react)
  [![NPM version](https://img.shields.io/npm/v/@ant-design/icons-react.svg?style=flat)](https://npmjs.org/package/@ant-design/icons-react)
  [![NPM downloads](http://img.shields.io/npm/dm/@ant-design/icons-react.svg?style=flat)](https://npmjs.org/package/@ant-design/icons-react)
  CDN: https://unpkg.com/@ant-design/icons-react/

### Angular
- [x] Angular Module
### Vue

- [x] Vue Component

**Comment by B3nnyL** [comment]
I'd like to help Vue component

**Comment by wzhudev** [comment]
Working on this for Angular.

**Comment by tangjinzhou** [comment]
@B3nnyL Already developing?

**Comment by B3nnyL** [comment]
@tangjinzhou In progress. I'll update by the end of this week.

**Comment by B3nnyL** [comment]
Sorry @tangjinzhou, my schedule is completely full this month, I'm not able to complete the plugin in two weeks, just FYI.   I don't want to break your release schedule. 
I'll keep working on it, which could be as an alternative svg icon library for AntDesign community.

**Comment by tangjinzhou** [comment]
@B3nnyL I will submit a version 1.0 first, you can optimize it.

**Comment by cyberalien** [comment]
I have something you might be interested in: open source SVG framework. It works similar to glyph fonts, but renders SVG and downloads only icons used on pages.

Iconify repository: https://github.com/iconify-design/
It supports your amazing icons set: https://iconify.design/icon-sets/ant-design/ 

That makes it easy to use your icons set on pages without generating fonts. For example, to use bell-outline icon from Ant Design all designer has to do is add Iconify script:

```<script src="https://code.iconify.design/1/1.0.0-rc7/iconify.min.js"></script>```

then add ant-design:bell-outline icon to page as ```span```:

```<span class="iconify" data-icon="ant-design:bell-outline"></span>```

It can be used with anything that uses HTML: usual HTML pages, React applications, Angular applications. It is very easy to use, it is light and fast.

Due to complexity of representing two tone icons (color is passed as currentColor, which is not possible with 2 tone icons, adding custom classes would require custom stylesheet, but framework is unified for many icon sets so custom css is not an option), only monotone icons are included: fill and outline. Fill icons use same name as in this repository, outline icons have -outline suffix.

edit: updated code
